// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALWve8F7B-DAeYlfYcxpPMucVNvHZIAb8',
    appId: '1:877783119277:web:bf54e45d10a29444c09d24',
    messagingSenderId: '877783119277',
    projectId: 'haenaem-65e32',
    authDomain: 'haenaem-65e32.firebaseapp.com',
    storageBucket: 'haenaem-65e32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQ7l0BxIGoyNHcmb79ybSHCaXiq2vv8g',
    appId: '1:877783119277:android:f23af125ab0eb12cc09d24',
    messagingSenderId: '877783119277',
    projectId: 'haenaem-65e32',
    storageBucket: 'haenaem-65e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6NtOY86JwriBd33oOvwrDzy5FnVoDOA',
    appId: '1:877783119277:ios:17b53bf5fa17cd84c09d24',
    messagingSenderId: '877783119277',
    projectId: 'haenaem-65e32',
    storageBucket: 'haenaem-65e32.firebasestorage.app',
    iosBundleId: 'com.example.haenaem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL6NtOY86JwriBd33oOvwrDzy5FnVoDOA',
    appId: '1:877783119277:ios:17b53bf5fa17cd84c09d24',
    messagingSenderId: '877783119277',
    projectId: 'haenaem-65e32',
    storageBucket: 'haenaem-65e32.firebasestorage.app',
    iosBundleId: 'com.example.haenaem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALWve8F7B-DAeYlfYcxpPMucVNvHZIAb8',
    appId: '1:877783119277:web:6fb696b6edab7be8c09d24',
    messagingSenderId: '877783119277',
    projectId: 'haenaem-65e32',
    authDomain: 'haenaem-65e32.firebaseapp.com',
    storageBucket: 'haenaem-65e32.firebasestorage.app',
  );
}
